version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./config/postgres/setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
